import { useRef } from "react";
import { motion, useInView, type Variants } from "framer-motion";
import Section from "@/components/ui/Section";
import GlowCard from "@/components/ui/GlowCard";
import Badge from "@/components/ui/Badge";
import { BoltFilledIcon, LayoutDashboardIcon, AnalyticsIcon, CheckIcon } from "@/components/ui/Icons";

const container: Variants = {
  hidden: {},
  show: { transition: { staggerChildren: 0.15 } },
};
const cardV: Variants = {
  hidden: { opacity: 0, y: 36, filter: "blur(4px)" },
  show:   { opacity: 1, y: 0,  filter: "blur(0px)", transition: { duration: 0.6, ease: [0.22, 1, 0.36, 1] } },
};

const FEATURES = [
  {
    Icon:    BoltFilledIcon,
    color:   "from-[#22C55E] to-[#16A34A]",
    glow:    "cyan" as const,
    badge:   "cyan" as const,
    tag:     "Real-Time Signals",
    title:   "Precision Signals, Zero Lag",
    desc:    "Every call is generated by our AI engine processing over 200 market indicators simultaneously — delivered to you in under 50ms with full entry, TP, and SL levels.",
    points:  ["AI-generated entry & exit points", "Covers Crypto, Forex, & Stocks", "Live Discord alert delivery", "89.7% verified historical win rate"],
  },
  {
    Icon:    LayoutDashboardIcon,
    color:   "from-[#16A34A] to-[#15803D]",
    glow:    "purple" as const,
    badge:   "purple" as const,
    tag:     "Auto Trading",
    title:   "Automated Execution Engine",
    desc:    "Connect your brokerage or exchange and let Trinity execute trades on your behalf. Rules-based automation with intelligent position sizing and risk controls.",
    points:  ["One-click TradingView automation", "Smart risk management built-in", "Works 24/7 — even while you sleep", "Full audit trail for every trade"],
  },
  {
    Icon:    AnalyticsIcon,
    color:   "from-emerald-400 to-teal-400",
    glow:    "cyan" as const,
    badge:   "green" as const,
    tag:     "Analytics",
    title:   "Institutional-Grade Analytics",
    desc:    "Track every position, backtest any strategy across years of data, and receive detailed performance reports that tell you exactly where your edge comes from.",
    points:  ["Multi-asset portfolio tracker", "Walk-forward strategy backtesting", "Daily & weekly performance reports", "Drawdown & risk-of-ruin metrics"],
  },
];

export default function FeaturesSection() {
  const ref = useRef<HTMLElement>(null);
  const inView = useInView(ref as React.RefObject<Element>, { once: true, amount: 0.15 });

  return (
    <Section id="features" className="bg-[#050508]" grid>
      <section ref={ref} aria-label="Platform features">
        {/* Heading */}
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.55, ease: [0.22, 1, 0.36, 1] }}
          className="text-center mb-16 max-w-2xl mx-auto"
        >
          <Badge variant="cyan" className="mb-4">
            Everything in one platform
          </Badge>
          <h2 className="font-display text-4xl sm:text-5xl font-extrabold tracking-tighter text-white mb-5 leading-[1.1]">
            Your entire trading edge,{" "}
            <span className="gradient-text">unified</span>
          </h2>
          <p className="text-gray-400 text-lg sm:text-xl leading-8 font-light">
            From raw signal generation to automated execution to post-trade analytics —
            Trinity handles every layer of your trading operation.
          </p>
        </motion.div>

        {/* Cards grid */}
        <motion.div
          variants={container}
          initial="hidden"
          animate={inView ? "show" : "hidden"}
          className="grid md:grid-cols-3 gap-6"
        >
          {FEATURES.map(({ Icon, color, glow, badge, tag, title, desc, points }) => (
            <motion.div key={title} variants={cardV}>
              <GlowCard glowColor={glow} className="h-full p-7 flex flex-col gap-5">
                {/* Icon */}
                <div className={`w-12 h-12 rounded-xl bg-gradient-to-br ${color} flex items-center justify-center text-white shadow-lg`}>
                  <Icon className="w-6 h-6" />
                </div>

                <div>
                  <Badge variant={badge} dot={false} className="mb-3 text-[11px]">
                    {tag}
                  </Badge>
                  <h3 className="font-display text-xl font-bold text-white mb-2 tracking-tight">{title}</h3>
                  <p className="text-sm text-gray-400 leading-relaxed">{desc}</p>
                </div>

                <ul className="mt-auto space-y-2" role="list">
                  {points.map(pt => (
                    <li key={pt} className="flex items-start gap-2 text-sm text-gray-300">
                      <CheckIcon className="w-4 h-4 text-[#22C55E] mt-0.5 flex-shrink-0" />
                      {pt}
                    </li>
                  ))}
                </ul>
              </GlowCard>
            </motion.div>
          ))}
        </motion.div>
      </section>
    </Section>
  );
}
