import LegalLayout, { LegalSection } from "@/components/layout/LegalLayout";

export default function TermsOfUse() {
  return (
    <LegalLayout title="Terms of Use" lastUpdated="March 20, 2026">

      <LegalSection title="1. Agreement to Terms">
        <p>
          By accessing or using the Trinity Trading AI software, website, or any associated service
          (collectively, the "Service"), you agree to be bound by these Terms of Use. If you do not
          agree, you must not use the Service. These terms apply to all visitors, users, and
          subscribers.
        </p>
      </LegalSection>

      <LegalSection title="2. Description of Service">
        <p>
          Trinity Trading AI provides an AI-powered trading signal and automation tool for retail
          traders on Windows 10/11. The software connects to supported brokers and executes or
          displays trading signals generated by our algorithmic models. Trinity is a software tool —
          it is not a licensed financial adviser, broker, fund manager, or investment firm.
        </p>
      </LegalSection>

      <LegalSection title="3. Licence Grant">
        <p>
          Upon successful payment and delivery of a licence key, Trinity grants you a limited,
          non-exclusive, non-transferable, revocable, single-seat licence to install and use the
          software on one (1) Windows 10 or Windows 11 PC for the duration of your active
          subscription.
        </p>
        <p className="mt-2">You may not:</p>
        <ul className="list-disc list-outside ml-5 space-y-1.5 mt-2">
          <li>Share, resell, sublicense, or distribute your licence key to any third party.</li>
          <li>Reverse-engineer, decompile, disassemble, or modify the software.</li>
          <li>Use the software on more than one machine concurrently.</li>
          <li>Use the software for any illegal, fraudulent, or market-manipulative activity.</li>
        </ul>
      </LegalSection>

      <LegalSection title="4. Payment &amp; Billing">
        <p>
          Subscriptions are billed monthly, in advance. The initial purchase price is displayed at
          checkout; renewal pricing is shown clearly before you purchase. Subscriptions
          automatically renew each month at the renewal rate unless you cancel before the renewal
          date.
        </p>
        <p className="mt-2">
          Payments are processed via NOWPayments in cryptocurrency. All prices are quoted in USD.
          The final crypto amount is calculated at the prevailing exchange rate at the time of
          invoice creation and is locked in for the duration of that invoice.
        </p>
        <p className="mt-2">
          Failed or incomplete payments result in immediate licence suspension. You may re-subscribe
          at any time.
        </p>
      </LegalSection>

      <LegalSection title="5. Acceptable Use">
        <p>You agree to use the Service only for lawful purposes and in compliance with all
          applicable laws and regulations in your jurisdiction, including but not limited to those
          governing financial trading and automated trading systems. You must not use the Service
          to engage in any form of market manipulation, money laundering, or fraudulent trading.
        </p>
      </LegalSection>

      <LegalSection title="6. Intellectual Property">
        <p>
          All content, software, logos, designs, and materials made available through the Service
          are the exclusive property of Project Trinity or its licensors and are protected by
          applicable copyright, trademark, and intellectual property laws. Nothing in these Terms
          grants you any right to use Trinity's branding or intellectual property beyond what is
          necessary to use the licensed software.
        </p>
      </LegalSection>

      <LegalSection title="7. Disclaimer of Warranties">
        <p>
          The Service is provided on an <span className="text-white font-medium">"AS IS"</span> and{" "}
          <span className="text-white font-medium">"AS AVAILABLE"</span> basis without any
          warranties of any kind, express or implied, including but not limited to warranties of
          merchantability, fitness for a particular purpose, accuracy of trading signals, or
          uninterrupted availability. We do not warrant that the software will be error-free or
          that signals will generate profits.
        </p>
        <p className="mt-2">
          AI-generated signals are informational only and do not constitute financial advice.
          Past performance does not guarantee future results.
        </p>
      </LegalSection>

      <LegalSection title="8. Limitation of Liability">
        <p>
          To the fullest extent permitted by applicable law, Project Trinity and its affiliates,
          officers, employees, and licensors shall not be liable for any indirect, incidental,
          special, consequential, or punitive damages, including but not limited to trading losses,
          lost profits, data loss, or loss of goodwill, arising from your use of or inability to
          use the Service.
        </p>
        <p className="mt-2">
          In no event shall Trinity's total aggregate liability to you exceed the total amount you
          paid to Trinity in the thirty (30) days immediately preceding the event giving rise to
          the claim.
        </p>
      </LegalSection>

      <LegalSection title="9. Termination">
        <p>
          We reserve the right to suspend or terminate your licence and access to the Service at
          any time, with or without notice, if you breach these Terms or engage in any activity
          that we reasonably believe is harmful to Trinity, its users, or third parties.
        </p>
        <p className="mt-2">
          You may cancel your subscription at any time by contacting support before your next
          renewal date. Upon cancellation, your licence remains active until the end of the current
          paid period. No partial-month refunds are issued outside of our Refund Policy.
        </p>
      </LegalSection>

      <LegalSection title="10. Governing Law">
        <p>
          These Terms shall be governed by and construed in accordance with applicable law.
          Any disputes arising under these Terms shall first be attempted to be resolved
          informally by contacting us via Telegram or email. If informal resolution fails,
          disputes shall be submitted to binding arbitration.
        </p>
      </LegalSection>

      <LegalSection title="11. Changes to These Terms">
        <p>
          We reserve the right to modify these Terms at any time. Material changes will be
          communicated by updating the "Last updated" date. Your continued use of the Service
          after such changes constitutes your acceptance of the revised Terms.
        </p>
      </LegalSection>

      <LegalSection title="12. Contact Us">
        <p>
          Questions about these Terms? Reach us on Telegram at{" "}
          <a
            href="https://t.me/tti_mark_support"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#22C55E]/80 hover:text-[#22C55E] transition-colors"
          >
            t.me/tti_mark_support
          </a>{" "}
          or by email at{" "}
          <a
            href="mailto:support@trinitytradingai.com"
            className="text-[#22C55E]/80 hover:text-[#22C55E] transition-colors"
          >
            support@trinitytradingai.com
          </a>
          .
        </p>
      </LegalSection>

    </LegalLayout>
  );
}
